CREATE ROLE invenio1 with SUPERUSER LOGIN PASSWORD 'dbpass123';
CREATE DATABASE invenio1;
GRANT ALL PRIVILEGES ON DATABASE invenio1 TO invenio1;
CREATE ROLE invenio2 with SUPERUSER LOGIN PASSWORD 'dbpass123';
CREATE DATABASE invenio2;
GRANT ALL PRIVILEGES ON DATABASE invenio2 TO invenio2;
